// Supabase configuration. Use ONLY the public anon/publishable key here.
// NEVER put the service_role/secret key in frontend code.
const SUPABASE_URL="https://nllozkqelygctmvypijd.supabase.co";
const SUPABASE_ANON_KEY="sb_publishable_tZOJxU7fWrXPdbPhK0NB4w_0rOo_e9l";
const TEAMS=["Arsenal","Barcelona","Bayern Munich","Chelsea","Inter Milan","Liverpool","Manchester City","Manchester United","Paris Saint-Germain","Real Madrid","AC Milan","Juventus","Borussia Dortmund","Atletico Madrid","Tottenham Hotspur","Napoli"];
const configured=!SUPABASE_URL.includes("PASTE_")&&!SUPABASE_ANON_KEY.includes("PASTE_");
const db=configured?supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY):null;
const form=document.getElementById("registrationForm"),team=document.getElementById("team"),grid=document.getElementById("teamGrid"),list=document.getElementById("playersList"),count=document.getElementById("playerCount"),msg=document.getElementById("message"),submit=document.getElementById("submitBtn");
document.getElementById("year").textContent=new Date().getFullYear();
function message(t,c){msg.textContent=t;msg.className="message "+c}
function options(players){const taken=new Set(players.map(x=>x.team));team.innerHTML='<option value="">Choose an available team</option>';TEAMS.forEach(t=>{let o=document.createElement("option");o.value=t;o.textContent=taken.has(t)?t+" — TAKEN":t;o.disabled=taken.has(t);team.appendChild(o)})}
function teamBoard(players){const taken=new Set(players.map(x=>x.team));grid.innerHTML="";TEAMS.forEach(t=>{const yes=taken.has(t),d=document.createElement("div");d.className="teamCard "+(yes?"taken":"");d.innerHTML='<div class="teamTop"><span class="teamName"></span><span class="status">'+(yes?"TAKEN":"AVAILABLE")+'</span></div><small>'+(yes?"Reserved by a registered player":"Ready for selection")+"</small>";d.querySelector(".teamName").textContent=t;grid.appendChild(d)})}
function playersBoard(players){count.textContent=players.length+" player"+(players.length===1?"":"s")+" registered";if(!players.length){list.innerHTML='<div class="empty">No players registered yet. Be the first to choose a team.</div>';return}list.innerHTML="";players.forEach((p,i)=>{let d=document.createElement("div");d.className="player";d.innerHTML='<div class="num">'+String(i+1).padStart(2,"0")+'</div><div class="info"><strong></strong><span>Registered player</span></div><div class="info username"><strong></strong><span>eFootball username</span></div><div class="playerTeam"></div>';d.querySelectorAll("strong")[0].textContent=p.full_name;d.querySelectorAll("strong")[1].textContent=p.username;d.querySelector(".playerTeam").textContent=p.team;list.appendChild(d)})}
async function load(){if(!db){options([]);teamBoard([]);count.textContent="Supabase not configured";list.innerHTML='<div class="empty">Add your Supabase URL and public anon/publishable key in script.js.</div>';return}const {data,error}=await db.from("players").select("id,full_name,username,team,created_at").order("created_at",{ascending:true});if(error){
  console.error("SUPABASE ERROR:", error);
  message("Supabase error: " + error.message, "error");
  return;
}options(data);teamBoard(data);playersBoard(data)}
form.addEventListener("submit",async e=>{e.preventDefault();if(!db){message("Supabase is not configured yet. Add your project URL and public key in script.js.","error");return}const full_name=document.getElementById("fullName").value.trim().replace(/\s+/g," "),username=document.getElementById("username").value.trim().replace(/\s+/g," "),selected=team.value;if(full_name.length<2)return message("Please enter a valid full name.","error");if(username.length<2)return message("Please enter your eFootball username.","error");if(!selected)return message("Please select a team.","error");submit.disabled=true;submit.textContent="Registering...";const {error}=await db.from("players").insert({full_name,username,team:selected});if(error){console.error(error);message("Registration error: " + error.message, "error");await load()}else{form.reset();message("Registration successful! "+selected+" has been reserved for "+full_name+".","success");await load();document.getElementById("players").scrollIntoView({behavior:"smooth"})}submit.disabled=false;submit.textContent="Reserve My Team →"});
load();
if(db)db.channel("players-live").on("postgres_changes",{event:"*",schema:"public",table:"players"},load).subscribe();